# Generated by Django 5.1.2 on 2024-10-30 07:14

import appBackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(upload_to=appBackend.models.user_directory_path),
        ),
    ]
